# The URL the site will be built for
base_url = "https://truehumandesign.net"
title = "truehumandesign"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
toc = true
use_cdn = false
theme = "auto"

stylesheets = ["override.css"]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/truehumandesign/", icon = "github" },
]
